services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: ecommerce-sqlserver
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "Your_strong_password123!"
    ports:
      - "1433:1433"
    volumes:
      - sqlserver-data:/var/opt/mssql
    healthcheck:
      test: ["CMD-SHELL", "/opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P 'Your_strong_password123!' -C -Q 'SELECT 1' || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 20

  orderservice:
    build:
      context: .
      dockerfile: src/OrderService/Dockerfile
    environment:
      ASPNETCORE_URLS: http://+:8080
      ConnectionStrings__OrderDb: "Server=sqlserver,1433;Database=OrderDb;User Id=sa;Password=Your_strong_password123!;TrustServerCertificate=True;"
      Services__Inventory: "http://inventoryservice:8080"
      Services__Payment: "http://paymentservice:8080"
    ports:
      - "5001:8080"
    depends_on:
      sqlserver:
        condition: service_healthy
      inventoryservice:
        condition: service_started
      paymentservice:
        condition: service_started

  inventoryservice:
    build:
      context: .
      dockerfile: src/InventoryService/Dockerfile
    environment:
      ASPNETCORE_URLS: http://+:8080
      ConnectionStrings__InventoryDb: "Server=sqlserver,1433;Database=InventoryDb;User Id=sa;Password=Your_strong_password123!;TrustServerCertificate=True;"
    ports:
      - "5002:8080"
    depends_on:
      sqlserver:
        condition: service_healthy

  paymentservice:
    build:
      context: .
      dockerfile: src/PaymentService/Dockerfile
    environment:
      ASPNETCORE_URLS: http://+:8080
      ConnectionStrings__PaymentDb: "Server=sqlserver,1433;Database=PaymentDb;User Id=sa;Password=Your_strong_password123!;TrustServerCertificate=True;"
    ports:
      - "5003:8080"
    depends_on:
      sqlserver:
        condition: service_healthy

volumes:
  sqlserver-data:
