using Microsoft.EntityFrameworkCore;
using OrderService.Domain;

namespace OrderService.Infrastructure;

//public sealed class OrderDbContext(DbContextOptions<OrderDbContext> options) : DbContext(options)
//{
//    public DbSet<Order> Orders => Set<Order>();
//}

public class OrderDbContext : DbContext
{
 
    public OrderDbContext(
    DbContextOptions<OrderDbContext> options)
    : base(options)
    {
    }
    protected override void OnModelCreating(
    ModelBuilder modelBuilder)
    {
        // Keep any assembly-based configurations if present.
        modelBuilder.ApplyConfigurationsFromAssembly(
        typeof(OrderDbContext).Assembly);

        modelBuilder.Entity<Order>(entity =>
        {
            entity.ToTable("Orders");
            entity.HasKey(x => x.Id);
            // Id is generated by domain code (Guid.NewGuid()), not the database.
            entity.Property(x => x.Id).ValueGeneratedNever();
            entity.Property(x => x.CustomerId).IsRequired();
            entity.Property(x => x.Status).IsRequired();
            entity.Property(x => x.CreatedAtUtc).IsRequired();

            // Map to the private backing field so EF can populate Items when loading.
            entity.Metadata.FindNavigation(nameof(Order.Items))!
                .SetPropertyAccessMode(PropertyAccessMode.Field);

            entity.OwnsMany(x => x.Items, item =>
            {
                item.ToTable("OrderItems");
                item.WithOwner().HasForeignKey("OrderId");
                item.HasKey(x => x.Id);
                // Id is generated by domain code (Guid.NewGuid()), not the database.
                item.Property(x => x.Id).ValueGeneratedNever();
                item.Property(x => x.ProductId).IsRequired();
                item.Property(x => x.Quantity).IsRequired();
                item.Property(x => x.UnitPrice).HasColumnType("decimal(18,2)").IsRequired();
            });
        });
    }

    public DbSet<Order> Orders => Set<Order>();
}